[core]
backend=drm
use-pixman=true
xwayland=true
shell=kiosk
idle-time=0

[xwayland]

[autolaunch]
#path=/usr/bin/weston-terminal
path=/usr/bin/chromium
watch=true

#[output]
#name=HDMI-A-1
#mode=current

#[output]
#name=HDMI-A-2
#mode=current
