[core]
backend=drm
xwayland=true
use-pixman=true
shell=kiosk
idle-time=0

[xwayland]

[autolaunch]
#path=/usr/bin/weston-simple-egl
path=/retroarch/bin/retroarch
watch=true

[output]
name=HDMI-A-1
mode=1920x1080@60
#mode=current

# VGA 2nd display
[output]
name=HDMI-A-2
#mode=640x480@60
mode=off
