[core]
backend=drm
xwayland=true
use-pixman=true
shell=kiosk
idle-time=0

[xwayland]

[autolaunch]
#path=/usr/bin/weston-simple-egl
path=/retroarch/scripts/retroarch.sh
watch=true

[shell]
cursor-size=48

# keep primary display
[output]
name=HDMI-A-1
mode=current
#transform=rotate-90

# VGA 2nd display
[output]
name=HDMI-A-2
mode=off
